import { MetadataRoute } from 'next'

const BASE = 'https://tools4free.site'

export default function sitemap(): MetadataRoute.Sitemap {
  const tools = [
    '/fancy-text',
    '/qr-generator',
    '/password-generator',
    '/unit-converter',
    '/word-counter',
    '/timezone-converter',
    '/image-compressor',
    '/json-formatter',
    '/lorem-generator',
    '/case-converter',
    '/hash-generator',
    '/gradient-generator',
    '/base64',
    '/diff-checker',
    '/regex-tester',
    '/emoji-picker',
    '/color-picker',
    '/markdown-editor',
    '/favicon-generator',
    '/screenshot-mockup',
    // Niche pages
    '/instagram-fonts',
    '/cursive-text',
    '/bold-text',
    '/aesthetic-text',
    '/strikethrough-text',
    '/wifi-qr-code',
    '/menu-qr-code',
    '/whatsapp-qr-code',
    '/kg-to-lbs',
    '/cm-to-inches',
    '/celsius-to-fahrenheit',
    '/miles-to-km',
    '/strong-password',
    '/random-password',
    '/compress-png',
    '/compress-jpeg',
    '/json-validator',
    '/json-minifier',
    '/character-counter',
    '/uppercase-converter',
    // French pages
    '/fr/texte-style',
    '/fr/generateur-qr-code',
    '/fr/generateur-mot-de-passe',
    '/fr/convertisseur-unites',
    '/fr/compteur-mots',
    '/fr/compresser-image',
    '/fr/formateur-json',
    '/fr/convertisseur-majuscules',
    '/fr/generateur-lorem-ipsum',
    '/fr/generateur-degrade-css',
    // Spanish pages
    '/es/letras-bonitas',
    '/es/generador-qr',
    '/es/generador-contrasena',
    '/es/convertidor-unidades',
    '/es/contador-palabras',
    '/es/compresor-imagen',
    '/es/formateador-json',
    '/es/conversor-mayusculas',
    '/es/generador-lorem',
    '/es/generador-degradado-css',
    // Portuguese pages
    '/pt/texto-estilizado',
    '/pt/gerador-qr',
    '/pt/gerador-senha',
    '/pt/conversor-unidades',
    '/pt/contador-palavras',
    '/pt/compressor-imagem',
    '/pt/formatador-json',
    '/pt/conversor-maiusculas',
    '/pt/gerador-lorem',
    '/pt/gerador-gradiente-css',
  ]

  return [
    { url: BASE, lastModified: new Date(), changeFrequency: 'monthly', priority: 1 },
    ...tools.map(tool => ({
      url: `${BASE}${tool}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.9,
    })),
  ]
}
